### ISSUE TITLE
Kojifiles toplink/ are forbidden (403)

### ISSUE THREAD

**Issue by TristanCacqueray** [kostyrevaa/ansible-koji-hub#4]
Hello,

When trying to install packages from a repo published at /kojifiles/repos, yum tries to access:
  /kojifiles/repos/my_target/latest/x86_64/toplink/   which is a symlink to /mnt/koji. And this is failing with 403 Forbidden because toplink/ and /mnt/koji are not the same owner.

Anychance to make /mnt/koji apache owned or change the httpd's Directory options from SymLinksIfOwnerMatch to FollowSymlinks ?

**Comment by kostyrev** [comment]
You should not try to use packages from /kojifiles/repos. Those are for internal koji use only.
You should take a look at [mash](http://www.devops-blog.net/koji/getting-rpm-built-by-koji-into-yum-able-repo)

**Comment by TristanCacqueray** [comment]
Oh my bad then, thank you for the pointer!
